### PR TITLE
Fix handling of ip reservations if VLAN or prefix is not ready yet

### PR DESCRIPTION
**Pull request by anx-mschaefer**
### Description

Fixes race condition in new ip address reserve feature and prepares changelog for release.

### Checklist

* [x] added release notes to `Unreleased` section in [CHANGELOG.md](CHANGELOG.md), if user facing change

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by LittleFox94** [comment]
Two comments:

* could you try do something about the codeclimate issue?
* having a PR that fixes something and prepares the release is fine, but the PR title should be "fix something" and not "prepare release" in that case

**Comment by anx-mschaefer** [comment]
> * could you try do something about the codeclimate issue?

extracted the reserve logic into its own function.. but "new" codeclimate issues resurfaced. i don't think that breaking up the `resourceIPAddressReserveAvailableAddress` function further improves complexity/maintainability, but please let me know if you disagree :)

**Comment by LittleFox94** [comment]
I'm trying something to improve the code quality btw

**Comment by LittleFox94** [comment]
@anx-mschaefer ptal at the refactor-resource-ip-address branch I pushed, it's based on your branch here but does some refactoring .. who would've guessed based on the branches name ^^

**Comment by anx-mschaefer** [comment]
> @anx-mschaefer ptal at the refactor-resource-ip-address branch I pushed, it's based on your branch here but does some refactoring .. who would've guessed based on the branches name ^^

IMHO complexity increased on that branch and codeclimate will likely complain with that version as well (too nested & too many returns). We should probably call d.SetId earlier to not leak resource references on error.

Im ok with using the refactored version, but I think we should set the ID as soon as we know it.

**Comment by LittleFox94** [comment]
We are not quite certain, if after this refactor, errors are still leading to a tainted resource with the `id` set correctly. After this came up, I adapted the code a bit to account for that, but was so far unable to provoke an error to test this.

**Comment by 89Q12** [comment]
Using this tf configuration:
```
data "anxcloud_core_location" "anx04" {
  code = "ANX04"
}

resource "anxcloud_vlan" "example" {
  location_id          = data.anxcloud_core_location.anx04.id
  vm_provisioning      = true
  description_customer = "example-terraform"
}

resource "anxcloud_network_prefix" "v4" {
  vlan_id              = anxcloud_vlan.example.id
  location_id          = data.anxcloud_core_location.anx04.id
  ip_version           = 4
  netmask              = 30
  description_customer = "example-terraform"
}

resource "anxcloud_network_prefix" "v6" {
  vlan_id              = anxcloud_vlan.example.id
  location_id          = data.anxcloud_core_location.anx04.id
  ip_version           = 6
  netmask              = 126
  description_customer = "example-terraform"
}

resource "anxcloud_ip_address" "v4" {
vlan_id = anxcloud_vlan.example.id
}

resource "anxcloud_ip_address" "v6" {
  vlan_id = anxcloud_vlan.example.id
}
```
I get these errors after 15min, however it can create everything except the IPs:
```
│ Error: reserve endpoint returned an error: could not execute IP address reserve random post request: received error from api: {Code:400 Message:Bad Request: Not enough free Addresses available. Requested: 1 Validation:map[]}
│ 
│   with anxcloud_ip_address.v4,
│   on main.tf line 44, in resource "anxcloud_ip_address" "v4":
│   44: resource "anxcloud_ip_address" "v4" {
│ 
╵
╷
│ Error: reserve endpoint returned an error: could not execute IP address reserve random post request: received error from api: {Code:400 Message:Bad Request: Not enough free Addresses available. Requested: 1 Validation:map[]}
│ 
│   with anxcloud_ip_address.v6,
│   on main.tf line 48, in resource "anxcloud_ip_address" "v6":
│   48: resource "anxcloud_ip_address" "v6" {
│ 

```

**Review by 89Q12 — CHANGES_REQUESTED** [review]
LGTM, but please remove the date from the changelog and create a separate release PR.

**Review by 89Q12 — APPROVED** [review]

**Pull request merged**
